### ISSUE TITLE
modifs pour que ca marche sur raspberry (en urgence)

### ISSUE THREAD

**Issue by jblb** [haum/dhaumadi#1]
upgrade python en 3.6 ( compile)
ajouter la soudnfont a la ligne de commande de fluidsynth
installation de pyserial pour python 3.6
modif de la ligne de commande du service dhaumadi pour utiliser python 3.5

**Comment by jblb** [comment]
mettre le bouton sur "ON" sur les enceintes

**Comment by jblb** [comment]
intaller la commande de jeu dans un fichier bash appelé par le service au démarrage car pas de prise en compte du | par celle ci

**Comment by jblb** [comment]
intaller la commande de jeu dans un fichier bash appelé par le service au démarrage car pas de prise en compte du | par celle ci

**Comment by matael** [comment]
C'est règlé ça hein ? C'était pour Teriaki uniquement ?

**Comment by jblb** [comment]
python 3.6 c'est OK
ajouter la soudnfont a la ligne de commande de fluidsynth c'est fait
le fichier bach c'est le start.sh c'est donc fait

**Comment by matael** [comment]
Donc on ferme !

**Comment by jblb** [comment]
cette issue était faite pour garder une trace de ce que l'on faisais et pourquoi elle peut etre fermée ;-)

**Comment by matael** [comment]
Au besoin, Github a ajouté l'outil "Projets" qui permet de faire des kanban. Ça me semblerait plus pertinent pour ce genre de trucs :)

**Comment by JackDesBwa** [comment]
L'installation de l'environnement sur la raspberry pi est automatisée via puppet.
Ces modifications ne sont pas dans cette procédure => réouvert

**Comment by matael** [comment]
Tiens, on a pas le/les manifest(s) Puppet => il faudrait les ajouter ici.

**Comment by jblb** [comment]
quelqu'un sais ou il faut que j'aille chercher le/les manifest(s) Puppet sur la carte SD qui etait dans le pi que je mette ça là

**Comment by neomilium** [comment]
Je pense qu'ils sont uniquement sur le serveur du HAUM
