### ISSUE TITLE
connecter les LEDs directement sur le raspberry pi

### ISSUE THREAD

**Issue by jblb** [haum/dhaumadi#2]
plusieurs fois lors de la présentation de la structure aux siestes Teriaki la connexion wifi entre le raspberry et les led est tombée et a donc interrompu le jeu...
l'idée c'est donc de piloter directement les leds avec le pi, par exemple avec cette bibliothèque:  https://github.com/jgarff/rpi_ws281x

**Comment by matael** [comment]
La librairie que linke @jblb demande de blacklister `snd_bcm2835` ce qui me semble un peu compremettre le côté "son" du projet. La discussion sur IRC a mené a :
- on peut utiliser une interface externe pour le son
- ça a été testé sur un pi0 mais pas sur un pi3 -> a tester rapidement

Ça impliquera de modifier aussi `PadsManager` dans game/game.py ligne 111

**Comment by jblb** [comment]
je fait marcher le jeux sur un pi0 avec une interface son externe sans avoir rien modifier au code

**Comment by matael** [comment]
Ah ben si t'arrives à passer de "on utilise des laumios" à "on passe par SPI" sans toucher au code, je te paye une 🍺  !

**Comment by jblb** [comment]
j'avais pris ta demande modif de game/game.py ligne 111 et suivante pour la gestion du son :-(
effectivement qu'il faudra la modifier si on passe par SPI pour commander les leds

**Comment by JackDesBwa** [comment]
Je n'ai pas testé la bibliothèque, mais son Readme indique explicitement qu'elle peut utiliser le SPI et que dans ce cas, il n'y a pas besoin de couper le son.

J'avais étudié la faisabilité via SPI et les indices du Readme suggèrent que l'auteur est arrivé à la même conclusion que moi. De plus, d'autres passages indiquent  qu'il a effectivement testé avec succès.

Je suggère que nous utilisions cette voie pour éviter d'ajouter une prothèse de voix là où elle est manifestement superflue.

**Comment by JackDesBwa** [comment]
Techniquement, il est possible de ne pas modifier le code de game.py pour faire fonctionner la nouvelle solution. Cependant, je n'exposerai pas la méthode tordue de crainte qu'elle ne soit  envisagée comme viable.

**Comment by matael** [comment]
Je la veux bien quand même.... oh. Tu penses à... "ne pas modifier le code **de game.py**" : ça sent le truc *vraiment* dégueu là, genre faire importer un "Laumio" un peu modifié... pas beau.

**Comment by JackDesBwa** [comment]
Je parlais plus généralement de ne pas modifier le code existant.
Mais non, on n'expose pas en public des bricolages pareils.

**Comment by matael** [comment]
Bon, là, on a un truc qui marche entièrement sur Raspberry pi. Je ferme cette issue !
